pipeline{
    agent any
         tools{
              maven 'maven-3.6.3'
               }
     stages{
          stage ("checkout")  {
              steps{
       checkout scmGit(branches: [[name: '*/Assignment6']], extensions: [], userRemoteConfigs: [[credentialsId: '8a396b05-d7fd-4b95-93cc-6b74947df9a3', url: 'https://git.nagarro.com/GITG00641/Java/3202807.git']])}
          }
          stage('build'){
            steps{
            bat 'cd AdvanceJavaAssignment5/Assignment5Application1 && mvn -f  pom.xml clean install'
                 }
            }
     }
}

